{
 "title": "Power",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Current Power Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(plug_current_power)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Peak Power Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max by (plug_name) (max_over_time(plug_current_power[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Minimum Power Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(min by (plug_name) (min_over_time(plug_current_power[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Power Usage",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "mwatt" } },
   "targets": [
    {
     "expr": "sum by (plug_name) (plug_current_power)",
     "legendFormat": "{{plug_name}}"
    },
    { "expr": "sum (plug_current_power)", "legendFormat": "total" }
   ]
  },
  {
   "title": "Plug Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "targets": [
    {
     "expr": "avg by (plug_name) (last_over_time(plug_status[$__interval]))",
     "legendFormat": "{{plug_name}}"
    }
   ]
  },
  {
   "title": "Plug Overheated",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "targets": [
    {
     "expr": "avg by (plug_name) (last_over_time(plug_overheated[$__interval]))",
     "legendFormat": "{{plug_name}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "clamp_max(avg by(plug_name) (increase(plug_on_time[1m])) / 60, 1)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}