{{- if ne .Values.config.existingSecret "" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tapo-prometheus-exporter.secretName" . }}
  labels:
    {{- include "tapo-prometheus-exporter.labels" . | nindent 4 }}
stringData:
  config.yaml: |
    {{ .Values.config.value | nindent 4 }}
{{- end }}
