{{- if .Values.prometheus.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "tapo-prometheus-exporter.fullname" . -}}-monitor
  labels:
    {{- include "tapo-prometheus-exporter.serviceMonitorLabels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "tapo-prometheus-exporter.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: /metrics
{{- end }}
