name: Build & Push

on:
  push:
    branches:
      - 'main'
      - 'develop'

jobs:
  build:
    name: Build and Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '^1.21.1'
          check-latest: true
          cache-dependency-path: src/go.sum

      - name: Declare some variables
        id: vars
        shell: bash
        run: |
          echo "branch=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_OUTPUT
          echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          echo "build_timestamp=$(date '+%Y-%m-%dT%H:%M:%S')" >> $GITHUB_OUTPUT
          echo "version=0.0.0" >> $GITHUB_OUTPUT

      - name: Install dependencies
        working-directory: src
        run: go mod download

      - name: Install golint
        working-directory: src
        run: go install golang.org/x/lint/golint@latest

      - name: lint
        working-directory: src
        run: golint

      - name: vet
        working-directory: src
        run: go vet

      - name: Build
        working-directory: src
        env:
          CGO_ENABLED: 0
        run: go build -ldflags="-s -w -X 'main.version=${{ steps.vars.outputs.version }}' -X 'main.commitHash=${{ steps.vars.outputs.branch }}-${{ steps.vars.outputs.sha_short }}' -X 'main.buildTimestamp=${{ steps.vars.outputs.build_timestamp }}'" -o tapo-prometheus-exporter .

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker build & push
        working-directory: src
        run: |
          docker image build -t "hfoxy4/tapo-prometheus-exporter:${{ steps.vars.outputs.branch }}" -t "hfoxy4/tapo-prometheus-exporter:${{ steps.vars.outputs.branch }}-${{ steps.vars.outputs.sha_short }}" .
          docker push -a "hfoxy4/tapo-prometheus-exporter"

      - uses: azure/setup-helm@v3
        with:
          version: 'v3.11.1'
        id: install

      - name: Update chart version
        working-directory: chart
        run: |
          sed -i "s/version: .*/version: ${{ steps.vars.outputs.version }}/g" Chart.yaml
          sed -i "s/appVersion: .*/appVersion: ${{ steps.vars.outputs.version }}/g" Chart.yaml

      - name: Helm lint
        working-directory: chart
        run: helm lint

      - name: Helm package
        working-directory: chart
        run: helm package tapo-prometheus-exporter